name: mycroft-precise
adopt-info: mycroft-precise
summary: Mycroft Precise
description: Mycroft Precise, a wake word spotter.
base: core18
grade: stable
confinement: strict
build-packages: [python3-dev, python3-setuptools, libtool, libffi-dev, libssl-dev, autoconf, build-essential]
parts:
  alsa-mixin:
    build-packages:
    - libasound2-dev
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    stage-packages:
    - libslang2
    - libasound2
    - libasound2-plugins
    - libportaudio2
    - pulseaudio
    - alsa-utils
  mycroft-precise:
    after: [alsa-mixin]
    plugin: python
    python-version: python3
    source: https://github.com/MycroftAI/mycroft-precise.git
    source-type: git
    source-branch: dev
    override-pull: |
        snapcraftctl pull
        # Set version to setup.py version if current commit is the latest
        # tag, otherwise append "-dev" to the version string.
        set +e
        if [[ git describe --exact-match --tags $(git log -n1 --pretty='%h') ]]
        then
            VERSION=$(/usr/bin/python3 setup.py --version)
        else
            VERSION="$(/usr/bin/python3 setup.py --version)-dev"
        fi
        set -e
        snapcraftctl set-version $VERSION
    build-packages:
        - python-setuptools
        - python3-pip
        - curl
        - libopenblas-dev
        - python3-scipy
        - cython
        - libhdf5-dev
        - python3-h5py
        - portaudio19-dev
        - swig
        - libatlas-base-dev
    stage-packages:
        - libopenblas-base
        - python3
        - python3-scipy
        - cython
        - libhdf5-100
        - libhdf5-cpp-100
        - python3-h5py
        - swig
        - libatlas3-base
  hey-mycroft:
    plugin: dump
    source: https://github.com/MycroftAI/precise-data/raw/models/hey-mycroft.tar.gz
    source-type: tar
    organize:
        '*': /hey-mycroft/

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  mycroft-precise:
    plugs: [home]
    command: bin/precise-engine
  add-noise:
    plugs: [home]
    command: bin/precise-add-noise
  calc-threshold:
    plugs: [home]
    command: bin/precise-calc-threshold
  collect:
    plugs: [home, audio-record, audio-playback]
    command-chain:
    - snap/command-chain/alsa-launch
    command: bin/precise-collect
  convert:
    plugs: [home]
    command: bin/precise-convert
  eval:
    plugs: [home]
    command: bin/precise-eval
  engine:
    plugs: [home]
    command: bin/precise-engine
  graph:
    plugs: [home]
    command: bin/precise-graph
  listen:
    command-chain:
    - snap/command-chain/alsa-launch
    plugs: [home, audio-record, audio-playback]
    command: bin/precise-listen
  listen-pocketsphinx:
    command-chain:
    - snap/command-chain/alsa-launch
    plugs: [home, audio-record, audio-playback]
    command: bin/precise-listen-pocketsphinx
  simulate:
    plugs: [home]
    command: bin/precise-simulate
  test:
    plugs: [home]
    command: bin/precise-test
  test-pocketsphinx:
    plugs: [home]
    command: bin/precise-test-pocketsphinx
  train:
    plugs: [home]
    command: bin/precise-train
  train-generated:
    plugs: [home]
    command: bin/precise-train-generated
  train-incremental:
    plugs: [home]
    command: bin/precise-train-incremental
  train-optimize:
    plugs: [home]
    command: bin/precise-train-optimize
  train-sampled:
    plugs: [home]
    command: bin/precise-train-sampled
